# Generated by Django 4.0.4 on 2022-05-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('album', models.CharField(max_length=250)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=300)),
                ('likes', models.IntegerField(default=0)),
                ('album_art', models.CharField(max_length=1000)),
            ],
        ),
    ]
